<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bycounter"
    nsURI="http://sdq.ipd.kit.edu/ByCounterModels/0.3" nsPrefix="ByCounter">
  <eSubpackages name="output" nsURI="http://sdq.ipd.kit.edu/ByCounterModels/Output/0.3"
      nsPrefix="ByCounter.Output">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Decorator&amp;nbsp;models&amp;nbsp;which&amp;nbsp;annotate&amp;nbsp;raw&amp;nbsp;resource&amp;nbsp;demands&amp;nbsp;to&amp;nbsp;AbstractInternalControlFlowActions."/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="OutputModelRepository" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="ResultCollection">
      <eStructuralFeatures xsi:type="ecore:EReference" name="requestResults" ordered="false"
          upperBound="-1" eType="#//output/RequestResult" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="countingResults" ordered="false"
          upperBound="-1" eType="#//output/CountingResult" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RequestResult">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resultCollection" ordered="false"
          upperBound="-1" eType="#//output/ResultCollection" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestId" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="countingResults" ordered="false"
          upperBound="-1" eType="#//output/CountingResult" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CountingResult">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrayCreationCounts"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="callerId" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodCallCounts" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodInvocationBeginning"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodReportingTime"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="observedElement" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="opcodeCounts" ordered="false"
          lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ownId" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifyingMethodName"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ThreadedCountingResult" eSuperTypes="#//output/CountingResult">
      <eStructuralFeatures xsi:type="ecore:EReference" name="spawnedThreadedCountingResults"
          ordered="false" upperBound="-1" eType="#//output/ThreadedCountingResult"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="threadId" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="input" nsURI="http://sdq.ipd.kit.edu/ByCounterModels/Input/0.3"
      nsPrefix="ByCounter.Input">
    <eClassifiers xsi:type="ecore:EClass" name="InstrumentationProfile" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eOperations name="SummationexcludesonlyallowedifsummationisactiveandaggregateInternalCallsTransparentlyistrue"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="self.summationExcludes->size()>0 implies self.aggregateInternalCallsTransparently=true&#xD;&#xA;"/>
        </eAnnotations>
        <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
          </eAnnotations>
        </eParameters>
        <eParameters name="context">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The cache of context-specific information."/>
          </eAnnotations>
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
            <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
            <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="definedLogicalSets" ordered="false"
          upperBound="-1" eType="#//input/LogicalSet" containment="true" eOpposite="#//input/LogicalSet/instrumentationProfile"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instrumentRecursively"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregateInternalCallsTransparently"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistInstrumentedClasses"
          ordered="false" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="intrumentationProfileRepository"
          ordered="false" eType="#//input/InstrumentationProfileRepository" eOpposite="#//input/InstrumentationProfileRepository/instrumentationProfile"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instrumentUsingLongCounters"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instrumentUsingBasicBlocks"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="traceAndIdentifyRequests"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="aggregationExcludes"
          ordered="false" upperBound="-1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//functions/Method"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="entitiesToInstrument"
          ordered="false" upperBound="-1" eType="#//input/EntityToInstrument" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LogicalSet" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="internalClasses" ordered="false"
          upperBound="-1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//types/GASTClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instrumentationProfile"
          ordered="false" lowerBound="1" eType="#//input/InstrumentationProfile" eOpposite="#//input/InstrumentationProfile/definedLogicalSets"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstrumentationProfileRepository"
        eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instrumentationProfile"
          ordered="false" upperBound="-1" eType="#//input/InstrumentationProfile"
          containment="true" eOpposite="#//input/InstrumentationProfile/intrumentationProfileRepository"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EntityToInstrument"/>
    <eClassifiers xsi:type="ecore:EClass" name="InstrumentedCodeArea" eSuperTypes="#//input/EntityToInstrument">
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//statements/Statement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" ordered="false" lowerBound="1"
          eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//statements/Statement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstrumentedMethod" eSuperTypes="#//input/EntityToInstrument">
      <eStructuralFeatures xsi:type="ecore:EReference" name="implementationOrDerived"
          ordered="false" upperBound="-1" eType="#//input/InstrumentedMethod" containment="true"
          eOpposite="#//input/InstrumentedMethod/declarationOrParent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declarationOrParent"
          ordered="false" eType="#//input/InstrumentedMethod" eOpposite="#//input/InstrumentedMethod/implementationOrDerived"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instrumentDerived" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="method" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//functions/Method"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstrumentedRegion" eSuperTypes="#//input/EntityToInstrument">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startLine" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopLine" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startMethod" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//functions/Method"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="stopMethod" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//functions/Method"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
