<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bycounter"
    nsURI="http://sdq.ipd.kit.edu/ByCounterModels/0.3" nsPrefix="ByCounter">
  <eSubpackages name="output" nsURI="http://sdq.ipd.kit.edu/ByCounterModels/Output/0.3"
      nsPrefix="ByCounter.Output">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Decorator&amp;nbsp;models&amp;nbsp;which&amp;nbsp;annotate&amp;nbsp;raw&amp;nbsp;resource&amp;nbsp;demands&amp;nbsp;to&amp;nbsp;AbstractInternalControlFlowActions."/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="OutputModelRepository" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resultCollection" ordered="false"
          upperBound="-1" eType="#//output/ResultCollection" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResultCollection">
      <eStructuralFeatures xsi:type="ecore:EReference" name="requestResults" ordered="false"
          upperBound="-1" eType="#//output/RequestResult" containment="true" eOpposite="#//output/RequestResult/resultCollection"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="countingResults" ordered="false"
          upperBound="-1" eType="#//output/CountingResult" containment="true" eOpposite="#//output/CountingResult/resultCollection"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RequestResult" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="countingResults" ordered="false"
          upperBound="-1" eType="#//output/CountingResult" containment="true" eOpposite="#//output/CountingResult/requestResult"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resultCollection" ordered="false"
          lowerBound="1" eType="#//output/ResultCollection" eOpposite="#//output/ResultCollection/requestResults"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CountingResult">
      <eStructuralFeatures xsi:type="ecore:EReference" name="callerId" ordered="false"
          lowerBound="1" eType="#//output/UUID" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The ID of the method that invoked the method of the result. Can be null if the caller was not instrumented."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodInvocationStartTime"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Time at which the method that produced this result was invoked."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="reportingTime" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Time at which the result was reported."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="observedElement" ordered="false"
          lowerBound="1" eType="#//input/EntityToInstrument"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="opcodeCounts" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="A list of counts for all possible opcodes, even if a particular opcode was not counted, i.e. the count is 0."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="methodId" ordered="false"
          lowerBound="1" eType="#//output/UUID" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The ID of the method of this result."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedMethodName"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resultCollection" ordered="false"
          eType="#//output/ResultCollection" eOpposite="#//output/ResultCollection/countingResults"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arrayCreationCounts"
          ordered="false" upperBound="-1" eType="#//output/ArrayCreationCount" containment="true"
          eOpposite="#//output/ArrayCreationCount/countingResult"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="methodCallCounts" ordered="false"
          upperBound="-1" eType="#//output/MethodCallCount" containment="true" eOpposite="#//output/MethodCallCount/countingResult"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requestResult" ordered="false"
          eType="#//output/RequestResult" eOpposite="#//output/RequestResult/countingResults"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UUID">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringRepresentation"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayCreationCount">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" ordered="false"
          lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeDescriptor" ordered="false"
          lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Descriptor of the type of the array elements."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfDimensions" ordered="false"
          lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrayType" ordered="false"
          lowerBound="1" eType="#//output/ArrayType">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The opcode of the array type."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="countingResult" ordered="false"
          lowerBound="1" eType="#//output/CountingResult" eOpposite="#//output/CountingResult/arrayCreationCounts"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ArrayType">
      <eLiterals name="INVALID">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Unknown type or object type."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="BOOLEAN" value="1"/>
      <eLiterals name="BYTE" value="2"/>
      <eLiterals name="CHAR" value="3"/>
      <eLiterals name="DOUBLE" value="4"/>
      <eLiterals name="FLOAT" value="5"/>
      <eLiterals name="INT" value="6"/>
      <eLiterals name="LONG" value="7"/>
      <eLiterals name="SHORT" value="8"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodCallCount">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedFunctionName"
          ordered="false" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" ordered="false"
          lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="function" ordered="false"
          eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//functions/Function">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Reference to the called function (if mapping is available)."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="countingResult" ordered="false"
          lowerBound="1" eType="#//output/CountingResult" eOpposite="#//output/CountingResult/methodCallCounts"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ThreadedCountingResult" eSuperTypes="#//output/CountingResult">
      <eStructuralFeatures xsi:type="ecore:EReference" name="spawnedThreadedCountingResults"
          ordered="false" upperBound="-1" eType="#//output/ThreadedCountingResult"
          containment="true" eOpposite="#//output/ThreadedCountingResult/threadedCountingResult"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="threadedCountingResult"
          ordered="false" eType="#//output/ThreadedCountingResult" eOpposite="#//output/ThreadedCountingResult/spawnedThreadedCountingResults"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="threadId" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="input" nsURI="http://sdq.ipd.kit.edu/ByCounterModels/Input/0.3"
      nsPrefix="ByCounter.Input">
    <eClassifiers xsi:type="ecore:EClass" name="InstrumentationProfile" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instrumentRecursively"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="When set, instruments methods called from the methods specified in &#xA;entitesToInstrument that  are not Java API methods (packages java.*, javax.* sun.*) and not  native methods."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="aggregationExcludes"
          ordered="false" upperBound="-1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//functions/Method"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="entitiesToInstrument"
          ordered="false" upperBound="-1" eType="#//input/EntityToInstrument" containment="true"
          eOpposite="#//input/EntityToInstrument/instrumentationProfile"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="intrumentationProfileRepository"
          ordered="false" eType="#//input/InstrumentationProfileRepository" eOpposite="#//input/InstrumentationProfileRepository/instrumentationProfile"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instrumentUsingLongCounters"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="When true, counters are long values instead of integers. Must be used for counting large execution frequencies. Setting this to false offers some performance benifits but can result in overflows."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instrumentUsingBasicBlocks"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="When true, bytecode instructions will be counted in groups made up of identified basic blocks. The execution numbers of single instructions are calculated after the execution. When false, every single bytecode instruction will be counted by an individual counter."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="provideJoinThreadsAbility"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="When true, allows ByCounter to wait for all threads spawned from instrumented methods to complete."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistInstrumentedClassesToOSPath"
          ordered="false" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="When set, classes will be written to the hereby specified directory."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="provideOnlineSectionActiveUpdates"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=" When true, the instrumentation for providing updates on the execution of user specified code sections is inserted."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="traceAndIdentifyRequests"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="RequestIDs are UUIDs used to track the method call graph across threads. They are created in a root method (a method called with no request ID) and then passed recursively on to all methods it calls. Note: Currently, constructors cannot be tracked."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstrumentationProfileRepository"
        eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="executionProfile" ordered="false"
          upperBound="-1" eType="#//input/ExecutionProfile" containment="true" eOpposite="#//input/ExecutionProfile/instrumentationProfileRepository"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instrumentationProfile"
          ordered="false" upperBound="-1" eType="#//input/InstrumentationProfile"
          containment="true" eOpposite="#//input/InstrumentationProfile/intrumentationProfileRepository"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExecutionProfile">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="addUpResultsRecursively"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="True, when result retrieval adds up counting results recursively.&#xA;This means that results for methods that call other methods include the counts of these called methods, i.e. of the entire calling tree.&#xA;When false, only the counts for operations done in the method itself - not those by called methods - are returned."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregateInternalCallsTransparently"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="waitForThreadsToFinnish"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="When true, execution tries to wait for all threads from instrumented methods to finish before returning."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="definedLogicalSets" ordered="false"
          upperBound="-1" eType="#//input/LogicalSet" containment="true" eOpposite="#//input/LogicalSet/executionProfile"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instrumentationProfileRepository"
          ordered="false" eType="#//input/InstrumentationProfileRepository" eOpposite="#//input/InstrumentationProfileRepository/executionProfile"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LogicalSet" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="internalClasses" ordered="false"
          upperBound="-1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//types/GASTClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="executionProfile" ordered="false"
          lowerBound="1" eType="#//input/ExecutionProfile" eOpposite="#//input/ExecutionProfile/definedLogicalSets"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstrumentedCodeArea" eSuperTypes="#//input/EntityToInstrument">
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//statements/Statement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" ordered="false" lowerBound="1"
          eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//statements/Statement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstrumentedMethod" eSuperTypes="#//input/EntityToInstrument">
      <eStructuralFeatures xsi:type="ecore:EReference" name="implementationOrDerived"
          ordered="false" upperBound="-1" eType="#//input/InstrumentedMethod" containment="true"
          eOpposite="#//input/InstrumentedMethod/declarationOrParent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declarationOrParent"
          ordered="false" eType="#//input/InstrumentedMethod" eOpposite="#//input/InstrumentedMethod/implementationOrDerived"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instrumentDerived" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="method" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//functions/Method"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstrumentedRegion" eSuperTypes="#//input/EntityToInstrument">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startLine" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Absolute line number in the file defining startMethod."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopLine" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Absolute line number in the file defining stopMethod."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startMethod" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//functions/Method">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Method in which startLine defines the begin of the instrumentation region."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="stopMethod" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/de.fzi.gast/model/gast.ecore#//functions/Method">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Method in which stopLine defines the end of the instrumentation region."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EntityToInstrument" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instrumentationProfile"
          ordered="false" eType="#//input/InstrumentationProfile" eOpposite="#//input/InstrumentationProfile/entitiesToInstrument"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
